#theme: jekyll-theme-slate
#title: Welcome to Abhishek's homepage!
#description: Feel free to bookmark this to keep an eye on my project updates

name: Abhishek Sanghai, Exploration mode on!
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
